; PlatformIO プロジェクト設定ファイル
;
;   ビルド設定: ビルドフラグ、ソースフィルター
;   書き込み設定: カスタムアップロードポート、速度、追加フラグ
;   ライブラリ設定: 依存関係、追加ライブラリ保存先
;   高度な設定: 追加スクリプト
;
; その他の設定項目や例については、以下のドキュメントを参照してください
; https://docs.platformio.org/page/projectconf.html

[env:seeed_xiao_esp32s3]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
monitor_speed = 115200
lib_deps =
  adafruit/Adafruit GFX Library@^1.11.11
  adafruit/Adafruit ST7735 and ST7789 Library@^1.11.0
